// Deterministic Annex-B access units for protocol and queue testing.
//
// These access units are structurally valid (start codes, NAL types and parameter-set
// placement) but intentionally are not advertised as visually decodable fixtures. Use
// rc-fakephone replay with fixtures generated by scripts/generate-video-fixtures.ps1
// for decoder and desktop-pixel verification.

#ifndef RCFAKEPHONE_SYNTHETIC_MEDIA_H
#define RCFAKEPHONE_SYNTHETIC_MEDIA_H

#include <cstdint>
#include <vector>

#include "rc/control.h"

namespace rcfakephone {

struct EncodedUnit {
  std::vector<uint8_t> payload;
  uint64_t ptsMicros = 0;
  uint64_t frameNumber = 0;
  bool keyframe = false;
};

class SyntheticMedia {
 public:
  explicit SyntheticMedia(rc::control::StreamConfig config, uint64_t firstPtsMicros = 0);

  EncodedUnit next(bool forceKeyframe = false);
  void reconfigure(rc::control::StreamConfig config);

 private:
  std::vector<uint8_t> makeH264(bool keyframe) const;
  std::vector<uint8_t> makeHevc(bool keyframe) const;
  std::vector<uint8_t> marker() const;

  rc::control::StreamConfig config_;
  uint64_t firstPtsMicros_ = 0;
  uint64_t frameNumber_ = 0;
};

}  // namespace rcfakephone

#endif  // RCFAKEPHONE_SYNTHETIC_MEDIA_H
